### ISSUE TITLE
yarn install 报错UNCAUGHT ERROR: Error: fuzzaldrin-plus_v0.6.0\CONTRIBUTING.md: Unexpected file name.

### ISSUE THREAD

**Issue by humbinal** [phobal/ivideo#61]
`yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info 7zip-bin-linux@1.3.1: The platform "win32" is incompatible with this module.
info "7zip-bin-linux@1.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-mac@1.0.1: The platform "win32" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
Native dependencies could not be checked

> ivideo@1.1.0 flow-typed D:\SoftWare\ivideo-1.1.1
> rimraf flow-typed/npm && flow-typed install --overwrite || true

• Found 87 dependencies in package.json to install libdefs for. Searching...
• flow-typed cache not found, fetching from GitHub...
UNCAUGHT ERROR: Error: fuzzaldrin-plus_v0.6.0\CONTRIBUTING.md: Unexpected file name. This directory can only contain test files or a libdef file named `fuzzaldrin-plus_v0.6.0.js`.
    at validationError (D:\SoftWare\ivideo-1.1.1\node_modules\flow-typed\dist\lib\validationErrors.js:14:11)
    at D:\SoftWare\ivideo-1.1.1\node_modules\flow-typed\dist\lib\npm\npmLibDefs.js:113:53
    at Array.forEach (<anonymous>)
    at extractLibDefsFromNpmPkgDir$ (D:\SoftWare\ivideo-1.1.1\node_modules\flow-typed\dist\lib\npm\npmLibDefs.js:95:23)
    at tryCatch (D:\SoftWare\ivideo-1.1.1\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (D:\SoftWare\ivideo-1.1.1\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (D:\SoftWare\ivideo-1.1.1\node_modules\regenerator-runtime\runtime.js:117:21)
    at tryCatch (D:\SoftWare\ivideo-1.1.1\node_modules\regenerator-runtime\runtime.js:65:40)
    at invoke (D:\SoftWare\ivideo-1.1.1\node_modules\regenerator-runtime\runtime.js:155:20)
    at D:\SoftWare\ivideo-1.1.1\node_modules\regenerator-runtime\runtime.js:165:13
'true' 不是内部或外部命令，也不是可运行的程序
或批处理文件。`

**Comment by phobal** [comment]
@humbinal 提供一下你的 node 和 npm 版本吧

**Comment by chenshaoling** [comment]
我也是报这个错 node v10.8.0，npm 6.2.0

**Comment by sujie056520** [comment]
> @humbinal 提供一下你的 node 和 npm 版本吧

也出现这个错误，node v8.11.1 ，npm 5.6.0。node版本问题吗？

**Comment by SailHe** [comment]
类似的错误, 不过有编译后的二进制文件, 且可以使用
```
• Found 87 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
UNCAUGHT ERROR: Error: formik_v2.x.x\README.md: Unexpected file name. This directory can only contain test files or a libdef file named `formik_v2.x.x.js`.
    at validationError (...\ivideo\node_modules\flow-typed\dist\lib\validationErrors.js:14:11)
    at ...\ivideo\node_modules\flow-typed\dist\lib\npm\npmLibDefs.js:113:53
    at Array.forEach (<anonymous>)
    at extractLibDefsFromNpmPkgDir$ (...\ivideo\node_modules\flow-typed\dist\lib\npm\npmLibDefs.js:95:23)
    at tryCatch (...\ivideo\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (...\ivideo\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (...\ivideo\node_modules\regenerator-runtime\runtime.js:117:21)
    at tryCatch (...\ivideo\node_modules\regenerator-runtime\runtime.js:65:40)
    at invoke (...\ivideo\node_modules\regenerator-runtime\runtime.js:155:20)
    at ...\ivideo\node_modules\regenerator-runtime\runtime.js:165:13
'true' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ivideo@1.1.4 flow-typed: `rimraf flow-typed/npm && flow-typed install --overwrite || true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ivideo@1.1.4 flow-typed script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ...\global_node_modules\cache\_logs\2019-12-28T10_47_44_022Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by hmg520cc** [comment]
https://www.hmg520.cc 红玫瑰社区 
视频站
https://www.tyjr.info 童颜巨乳  
https://www.zguifldh.com 醉鬼福利
http://www.fltv.buzz/  福利TV
https://www.mhnvl.com 梦幻女郎   
https://www.hmglt.pw 黑玫瑰影院
