### ISSUE TITLE
flash问题！！win10，flash问题！最新版本！

### ISSUE THREAD

**Issue by 91en** [phobal/ivideo#91]
flash问题！！win10，flash问题！最新版本！
各种不能播放不能解析！
提示没有安装flash！

**Comment by 91en** [comment]
$ yarn install                                                                   yarn install v1.13.0                                                             [1/4] Resolving packages...                                                      [2/4] Fetching packages...                                                       info 7zip-bin-linux@1.3.1: The platform "win32" is incompatible with this module .                                                                                info "7zip-bin-linux@1.3.1" is an optional dependency and failed compatibility c heck. Excluding it from installation.                                            info 7zip-bin-mac@1.0.1: The platform "win32" is incompatible with this module.  info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility che ck. Excluding it from installation.                                              info fsevents@1.1.3: The platform "win32" is incompatible with this module.      info "fsevents@1.1.3" is an optional dependency and failed compatibility check.  Excluding it from installation.                                                  [3/4] Linking dependencies...                                                    [4/4] Building fresh packages...                                                 success Saved lockfile.                                                          $ node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typ ed && npm run build-dll && electron-builder install-app-deps && node node_module s/fbjs-scripts/node/check-dev-engines.js package.json                                                                                                             > ivideo@1.1.0 flow-typed Z:\ivideo                                              > rimraf flow-typed/npm && flow-typed install --overwrite \|\| true                                                                                                 • Found 87 dependencies in package.json to install libdefs for. Searching...     • rebasing flow-typed cache...                                                   UNCAUGHT ERROR: Error: fuzzaldrin-plus_v0.6.0\CONTRIBUTING.md: Unexpected file n ame. This directory can only contain test files or a libdef file named `fuzzaldr in-plus_v0.6.0.js`.                                                                  at validationError (Z:\ivideo\node_modules\flow-typed\dist\lib\validationErr ors.js:14:11)                                                                        at Z:\ivideo\node_modules\flow-typed\dist\lib\npm\npmLibDefs.js:113:53           at Array.forEach ()                                                   at extractLibDefsFromNpmPkgDir$ (Z:\ivideo\node_modules\flow-typed\dist\lib\ npm\npmLibDefs.js:95:23)                                                             at tryCatch (Z:\ivideo\node_modules\regenerator-runtime\runtime.js:65:40)        at Generator.invoke [as _invoke] (Z:\ivideo\node_modules\regenerator-runtime \runtime.js:303:22)                                                                  at Generator.prototype.(anonymous function) [as next] (Z:\ivideo\node_module s\regenerator-runtime\runtime.js:117:21)                                             at tryCatch (Z:\ivideo\node_modules\regenerator-runtime\runtime.js:65:40)        at invoke (Z:\ivideo\node_modules\regenerator-runtime\runtime.js:155:20)         at Z:\ivideo\node_modules\regenerator-runtime\runtime.js:165:13                                                                                               > ivideo@1.1.0 build-dll Z:\ivideo                                               > cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_ modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --colors                                                                                  Hash: 8e8067b50085caba5590                                                       Version: webpack 3.10.0                                                          Time: 2496ms                                                                                   Asset     Size  Chunks                    Chunk Names              renderer.dev.dll.js  1.93 MB       0  [emitted]  [big]  renderer                 [./node_modules/electron-debug recursive] ./node_modules/electron-debug 160 byte s {0} [built]                                                                    [./node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-mod ule.js 596 bytes {0} [built]                                                        [0] dll renderer 12 bytes {0} [built]                                             + 373 hidden modules                                                                                                                                          WARNING in ./node_modules/electron-debug/index.js                                81:45-58 Critical dependency: the request of a dependency is an expression        @ ./node_modules/electron-debug/index.js                                         @ dll renderer                                                                                                                                                   WARNING in ./node_modules/electron-debug/index.js                                84:85-106 Critical dependency: the request of a dependency is an expression       @ ./node_modules/electron-debug/index.js                                         @ dll renderer                                                                    • electron-builder version=19.55.3                                               • loaded configuration file=package.json ("build" field)                         • installing production dependencies platform=win32 arch=x64 appDir=Z:\ivideo\ app                                                                              Done in 59.58s.
--
